# Generated by Django 2.2.2 on 2019-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moisture_threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.IntegerField(verbose_name=50)),
                ('threshold', models.IntegerField(verbose_name=50)),
            ],
        ),
    ]
